abjhelp/users/urls.py
from django.urls import path

from abjhelp.users import views as users_view
app_name = "users"
urlpatterns = [
    path(
        route="",
        view=users_view.DashboardView.as_view(),
        name='index'
    ),
   	path(
        route="disclaimer",
        view=users_view.DisclaimerView.as_view(),
        name='disclaimer'
    ),

   	path(
        route="solicitud-ayuda",
        view=users_view.HelpRequestView.as_view(),
        name='help-request'
    ),
   	path(
        route="gracias😬",
        view=users_view.ThanksView.as_view(),
        name='thanks'
    ),
    path(
        route="advisor",
        view=users_view.AdvisorView.as_view(),
        name='advisor'
    ),
    path(
        route="donante",
        view=users_view.DonorRequestView.as_view(),
        name='donor'
    ),
    path(
        route="disclaimer_donante",
        view=users_view.DisclaimerDonorView.as_view(),
        name='dislcaimer_donor'
    ),
    path(
        route="gracias_donante",
        view=users_view.ThanksDonorView.as_view(),
        name='thanks_donor'
    ),
    path(
        route="solicitudes",
        view=users_view.InformationView.as_view(),
        name='help-requests'
    ),
    path(
        route="detalle/<str:pk>/",
        view=users_view.RequestDetailView.as_view(),
        name='detail'
    ),

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("", include("abjhelp.users.urls", namespace="users")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]

abjhelp/users/models.py
"""User model."""

# Django
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator

# Utilities
from abjhelp.utils.models import AbjHelpModel

class User(AbjHelpModel, AbstractUser):
    """User model.

    Extend from Django's Abstract User, change the username field
    to email and add some extra fields.
    """

    email = models.EmailField(
        'email address',
        unique=True,
        error_messages={
            'unique': 'Ya existe un usuario con ese email.'
        }
    )

    first_name = models.CharField('first name', max_length=150, blank=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'first_name', 'last_name']

    def __str__(self):
        """Return username."""
        return self.username

    def get_short_name(self):
        """Return username."""
        return self.username

    class Meta:
        """Meta class."""

        verbose_name = "Usuario"
        verbose_name_plural = "Usuarios"


class HelpRequest(AbjHelpModel):
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    phone_number = models.CharField(max_length=255)
    address = models.TextField(blank=True, null=True)
    is_active = models.BooleanField(default=True)

    class Meta:
        """Meta class."""

        verbose_name = "Solicitud de ayuda"
        verbose_name_plural = "Solicitudes de ayuda"
    
    def __str__(self):
        return self.name

class DonorRequest(AbjHelpModel):
    name = models.CharField(max_length=255)
    phone_number = models.CharField(max_length=255)
    email = models.EmailField(blank=True, null=True)
    address = models.TextField(blank=True, null=True)
    is_active = models.BooleanField(default=True)

    class Meta:
        """Meta class."""

        verbose_name = "Registro colaborador"
        verbose_name_plural = "Registro colaboradores"
    
    def __str__(self):
        return self.name

abjhelp/utils/models.py
"""Django models utilities."""

# Django
from django.db import models


class AbjHelpModel(models.Model):
    """AbjHelp Ride base model.
    CRideModel acts as an abstract base class from which every
    other model in the project will inherit. This class provides
    every table with the following attributes:
        + created (DateTime): Store the datetime the object was created.
        + modified (DateTime): Store the last datetime the object was modified.
    """

    created = models.DateTimeField(
        'created at',
        auto_now_add=True,
        help_text='Date time on which the object was created.'
    )
    modified = models.DateTimeField(
        'modified at',
        auto_now=True,
        help_text='Date time on which the object was last modified.'
    )

    class Meta:
        """Meta option."""
        abstract = True 

        get_latest_by = 'created'
        ordering = ['-created', '-modified']

abjhelp/users/forms.py
"""User forms."""

from django import forms
from abjhelp.users.models import HelpRequest, DonorRequest


class HelpRequestForm(forms.Form):

    name = forms.CharField(
        min_length=2,
        max_length=50,
        label='Nombre',
        error_messages={
            'required': 'Este campo es requerido',
        },
        widget=forms.TextInput(attrs={
            'class': 'form-control',
        }),
    )
    description = forms.CharField(
        label='Descripción del pedido',
        required=False,
        error_messages={
            'required': 'Este campo es requerido',
        },
        widget=forms.Textarea(
            attrs={
                "rows": 5, "cols": 20,
                'class': 'form-control',
            }),
    )
    phone_number = forms.CharField(
        label='Número del celular de contacto',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
            }),
        error_messages={
            'required': 'Este campo es requerido',
        },
    )

    address = forms.CharField(
        min_length=2,
        max_length=50,
        label='¿Dónde estás ubicado?',
        required=False,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
        }),
    )

    def save(self):
        """Create help resquest."""
        data = self.cleaned_data
        help_request = HelpRequest.objects.get_or_create(**data)
        return help_request


class DonorRequestForm(forms.Form):

    name = forms.CharField(
        min_length=2,
        max_length=50,
        label='¿Cuál es tu nombre?',
        error_messages={
            'required': 'Este campo es requerido',
        },
        widget=forms.TextInput(attrs={
            'class': 'form-control',
        }),
    )

    phone_number = forms.CharField(
        label='Número de whatsapp',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
            }),
        error_messages={
            'required': 'Este campo es requerido',
        },
    )
    email = forms.EmailField(
        min_length=2,
        max_length=50,
        required=False,
        label='¿Cuál es tu correo?',
        widget=forms.TextInput(attrs={
            'class': 'form-control',
        }),
        error_messages={
            'invalid': 'Porfavor ingrese un correo válido',
        },
    )
    address = forms.CharField(
        label='¿Dónde estás ubicado?',
        required=False,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
            }),
    )

    def save(self):
        """Create Donor resquest."""
        data = self.cleaned_data
        donor_request = DonorRequest.objects.get_or_create(**data)
        return donor_request

abjhelp/users/views.py
"""Branches Views."""

# Django
from django.views.generic import TemplateView, FormView, DetailView
from django.urls import reverse_lazy

# Forms
from abjhelp.users.forms import HelpRequestForm, DonorRequestForm
from abjhelp.users.models import HelpRequest


class DashboardView(TemplateView):
    template_name = 'index.html'


class DisclaimerView(TemplateView):
    template_name = 'disclaimer.html'


class DisclaimerDonorView(TemplateView):
    template_name = 'disclaimer_donor.html'


class HelpRequestView(FormView):
    template_name = 'help_request.html'
    form_class = HelpRequestForm
    success_url = reverse_lazy('users:thanks')

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class DonorRequestView(FormView):
    template_name = 'donor_request.html'
    form_class = DonorRequestForm
    success_url = reverse_lazy('users:thanks_donor')

    def form_invalid(self, form):
        """If the form is invalid, render the invalid form."""
        return self.render_to_response(self.get_context_data(form=form))

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class ThanksView(TemplateView):
    template_name = 'thanks.html'


class ThanksDonorView(TemplateView):
    template_name = 'thank_donor.html'


class AdvisorView(TemplateView):
    template_name = 'legal_advisor.html'


class InformationView(TemplateView):
    template_name = 'information.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["helps"] = HelpRequest.objects.all()
        return context
    
class RequestDetailView(DetailView):
    template_name = 'detail.html'
    slug_field = 'pk'
    slug_url_kwarg = 'pk'
    queryset = HelpRequest.objects.all()
    context_object_name = 'help'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        help_request = self.get_object()
        context["whatsapp"] = f'https://wa.me/57{help_request.phone_number}?text=Hola+{help_request.name},+te+escribo+por+el+pedido+que+hiciste+en+la+app+Un+Convite+por+Abejorral+https://unconviteporabejorral.org/detalle/{help_request.pk}'
        return context
    

abjhelp/templates/detail.html
{% extends 'base.html' %}

{% load static %}
{% block content %}
<div class="page-content">
    <div class="container-fluid">
        <div class="col-xl-6 offset-lg-3">
            <a href="{% url 'users:help-requests' %}">Regresar</a>

            <div class="card overflow-hidden mt-2">
                <div class="bg-soft-primary">
                    <div class="row">
                        <div class="col-7">
                            <div class="text-primary p-3">
                                <h5 class="text-primary">Pedido #{{help.pk}}</h5>
                            </div>
                        </div>
                        <div class="col-5 align-self-end">
                            <img src="{% static 'backoffice/assets/images/profile-img.png' %}" alt="" class="img-fluid">
                        </div>
                    </div>
                </div>
            </div>
            <!-- end card -->

            <div class="card">
                <div class="card-body">
                    <h3 class="subtitle has-text-left">{{help.name|title}}</h3>
            
                    <p class="has-text-left is-size-6">{{help.description}}</p>
                    <h5 class="font-size-15 font-weight-bold">Ubicación: </h5>{{help.address}}
                    <h5 class="font-size-15 font-weight-bold mt-3">Contactar</h5>
                    <div class="row">
                        <div class="col-12 mt-3">
                            <a href="tel:+57{{help.phone_number}}"
                            class="btn btn-dark waves-effect waves-light mr-1">
                                <i class="bx bx-phone-outgoing font-size-24 align-middle mr-2"></i> Llamar
                            </a>
                            <a  href="{{whatsapp}}" class="btn btn-success waves-effect waves-light">
                                <i class="bx bxl-whatsapp  font-size-24 align-middle mr-2"></i> Whatsapp
                            </a>
                        </div>
                    </div>
                </div>
            
                
            </div>

        </div>
    </div>
</div>




{% endblock content %}

abjhelp/templates/disclaimer.html
{% extends 'base.html' %}


{% block content %}

<div class="page-content">
    <div class="container-fluid">
        <div class="col-xl-4 offset-lg-4">
            
            <a href="{% url 'users:index' %}">Regresar</a>
            <div class="card mt-0 pt-0">
                <div class="card-body mt-0 pt-0">
                    <h3 class="mt-0 pt-0 text-center">Políticas de uso</h3>

                    <div class="text-center mt-0 mb-0">
                        <div>
                            <i class="bx bx bx-user-voice   text-primary display-4"></i>
                        </div>
                        <h4>Importante</h4>
                        <p class="text-justify mt-0 mb-0">Esta es una plataforma ciudadana sin ánimo de lucro, que opera gracias
                            al aporte voluntario de personas como tú, que buscan transformar la vida de niños y
                            jóvenes del municipio de Abejorral. <a href="{% url 'users:advisor' %}" >Mas información</a></p>
                    </div>
                    
                    <div class="table-responsive text-center">
                        <h4>Cómo funciona?</h4>
                        <p class="text-justify">Según nuestro modelo de trabajo, tenemos que cargar algunos datos
                            personales (nombre, teléfono de contacto, y lo que necesitas). La información que se
                            suministre será 100% de acceso público. Esta plataforma te permite compartir tu pedido
                            para que más gente lo vea, y así lograr solventar tú necesidad.</p>
                    </div>
                    <a href="{% url 'users:help-request' %}"
                        class="btn btn-lg btn-block btn-success w-lg waves-effect waves-light"
                        style="color:white">Entendido</a>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock content %}
    

abjhelp/templates/disclaimer_donor.html
{% extends 'base.html' %}


{% block content %}

<div class="page-content">
    <div class="container-fluid">
        <div class="col-xl-4 offset-lg-4">
            <a href="{% url 'users:index' %}">Regresar</a>
            <div class="card  mt-0 pt-0">
                <div class="card-body  mt-0 pt-0">
                    <h3 class="mb-2 text-center  mt-0 pt-0">Políticas de uso</h3>

                    <div class="text-center  mt-0 pt-0">
                        <div>
                            <i class="bx bx bx-user-voice   text-primary display-4"></i>
                        </div>
                        <h4>Importante</h4>
                        <p class="text-justify">Esta es una plataforma ciudadana que depende totalmente de la buena voluntad de la gente. 
                                    No hay garantías de recibir ayuda sí o sí. 
                                    La información que aquí se carga va a ser 100% de acceso público. <a href="{% url 'users:advisor' %}" >Mas información</a></p>
                    </div>
               
                    <div class="table-responsive mt-4 text-center">
                        <h4>Cómo funciona?</h4>
                        <p class="text-justify">Si estás dispuesto a ayudar, tenés que completar los campos con tus datos 
                            (asegurate que todos sean correctos) en la plataforma de unconviteporabejorral.org 
                            </p>
                    </div>
                    <a href="{% url 'users:help-requests' %}"
                        class="btn btn-lg btn-block btn-success w-lg waves-effect waves-light"
                        style="color:white">Entendido</a>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock content %}
    

abjhelp/templates/donor_request.html
{% extends 'base.html' %}


{% block content %}

<div class="page-content">
    <div class="container-fluid">
        <div class="col-xl-4 offset-lg-4">
            <a href="{% url 'users:index' %}">Regresar</a>
            <div class="card">
                <div class="card-body">
                    <h3 class="mb-4 text-center">Datos Colaborador❤️</h3>
                    <form method="POST">
                        {% csrf_token %}
                        {{form.as_p}}
                        <button type="submit" class="btn btn-lg btn-block btn-info w-lg waves-effect waves-light" style="color:white">Solicitar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

abjhelp/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="page-content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-6 offset-lg-3 mb-3">
                <h4 class="text-center">¡Los Abejorraleños nos juntamos y entre todos colaboramos!</h4>

            </div>
            
            <div class="col-lg-4 offset-lg-2">
                <a href = "{% url 'users:disclaimer'%}">
                <div class="card border border-success">
                    <div class="card-header bg-transparent border-success">
                        <h5 class="my-0 text-success" style="font-size: x-large;"><i
                                class="mdi mdi-check-all mr-3"></i>Necesito ayuda</h5>
                    </div>
                    <div class="card-body mt-0 pt-0">
                        <h5>Si eres estudiante, padre de familia o tutor cuentanos tu necesidad.</h5>
                    </div>
                </div>
            </a>
            </div>
        </span>
            <div class="col-lg-4">
                <a href = "{% url 'users:dislcaimer_donor'%}">
                <div class="card border border-primary">
                    <div class="card-header bg-transparent border-primary">
                        <h5 class="my-0 text-primary" style="font-size: x-large;"><i
                                class="mdi mdi-bullseye-arrow mr-3"></i>Quiero ayudar</h5>
                    </div>
                    <div class="card-body mt-0 pt-0">
                        <h5 class="card-title mt-0 ">Únete a esta iniciativa y apoya a quien lo necesite.</h5>
                    </div>
                </div>
            </a>
            </div>

        </div>
        <!-- end row -->
    </div> <!-- container-fluid -->
</div>
{% endblock content %}

abjhelp/templates/information.html
{% extends 'base.html' %}


{% block content %}

{% block css %}
<style>
    .descrption{
        color: inherit
    }
    .descrption:hover{
        color: inherit;
    }
</style>
{% endblock css %}
    
<div class="page-content">
    <div class="container-fluid">
        <div class="col-xl-6 offset-lg-3">
            <div class="row">
                <a href="{% url 'users:index' %}">Regresar</a>
                <div class="col-12 text-center">
                    <div class="card-title">
                        <h3 class="mb-4">Listado de solicitudes</h3>
                    </div>
                </div>

                {% if helps  %}
                {% for help in helps  %}
                <div class="card" style="width: 100%;">
                    <div class="card-body pt-0">
                        <div>
                            <ul class="verti-timeline list-unstyled mt-4">
                                <li class="event-list ml-1 pl-0">
                                    <div class="media">
                                        <div class="mr-3">
                                            <i class="bx bx-message-alt-dots  h1 text-primary"></i>
                                        </div>
                                        <a href="{% url 'users:detail' help.pk %}" class="descrption">
                                        <div class="media-body">
                                            <div>
                                                <h5 class="font-size-14">{{help.name|title}}</h5>
                                                <p class="text-justify text-muted mb-0">
                                                    {{help.description|truncatechars:200 }} <a
                                                        href="{% url 'users:detail' help.pk %}">Leer Más</a>
                                                </p>
                                            </div>
                                            <div class="mt-2 border-top">
                                                <ul class="list-inline mt-3 mb-0">
                                                    <li class="list-inline-item mr-3">

                                                        {% if help.is_active %}
                                                        <span class="badge badge-primary">Disponible</span>

                                                        {% else %}
                                                        <span class="badge badge-success">Completado</span>
                                                        {% endif %}
                                                    </li>
                                                    <li class="list-inline-item mr-3" data-toggle="tooltip"
                                                        data-placement="top" title=""
                                                        data-original-title="Fecha de solicitud">
                                                        <i class="bx bx-calendar mr-1"></i>{{help.created|date:"d-m-Y"}}
                                                    </li>
                                                </ul>
                                            </div>
                                        </div>
                                    </a>
                                    </div>
                                </li>
                            </ul>

                        </div>
                    </div>
                </div>


                {% endfor %}

                {% endif %}
            </div>


        </div> <!-- container-fluid -->
    </div>
    <!-- End Page-content -->
</div>
{% endblock content %}

abjhelp/templates/legal_advisor.html
{% extends 'base.html' %}

{% load static %}
{% block content %} 
<div class="page-content">
    
    
    <div class="container-fluid">
        <div class="col-xl-12">
            <a href="{% url 'users:disclaimer' %}" class="btn btn-primary btn-lg enabled" role="button" aria-enabled="true">Regresar</a>
            <div class="content text-justify">
                
        
                <h1>AVISO LEGAL</h1>
                
                <h3>DISCLAIMER</h3>
                <p class="text-justify">Al acceder y utilizar la página web y a la base de datos de unconviteporabejorral.org, el usuario reconoce el efecto 
                legalmente vinculante de las siguientes condiciones de uso y de la cláusula de descargo de responsabilidad.<br>
                En caso de que el usuario no esté de acuerdo con estas condiciones de uso, no podrá acceder a la página web de unconviteporabejorral.org.</p>
                
                <h2>1. Información publicada en la página web </h2>
                
                <p>La información provista por unconviteporabejorral.org se basa exclusivamente en los aportes suministrados por los usuarios de la misma voluntarimente; 
                por lo tanto, la responsabilidad acerca de la veracidad de los datos publicados en la presente lista pública corresponde a cada usuario que haga uso de ella.</p>
                
                <h2>2. Descargo de responsabilidad</h2>
                
                <p lass="text-justify">unconviteporabejorral.org no se hace responsable de ninguna información errónea, incompleta o desactualizada publicada en esta página web.  <br>
                unconviteporabejorral.org no asume ninguna responsabilidad por el mal funcionamiento de la página web.<br>
                Quedan expresamente excluidas aquellas demandas de responsabilidad contra unconviteporabejorral.org que se refieran a daños directos 
                o indirectos de índole material o intelectual y que hayan sido causados por el acceso a esta página web y a sus contenidos y/o a otras 
                páginas web enlazadas en la misma y a sus contenidos, así como por la utilización o la no utilización de la información representada y/o por la utilización de información errónea o incompleta.<br>
                unconviteporabejorral.org esta diseñada para evitar ataques de Cross-Site Request Forgery (CSRF) en relación a la transmisión de datos. 
                Sin embargo, la transmisión de datos por internet no es completamente segura. Por lo tanto, la información publicada en la página web de unconviteporabejorral.org puede verse sometida a alteraciones 
                o interrupciones así como a violaciones de la seguridad y la confidencialidad. Por este motivo, unconviteporabejorral.org no asume ninguna responsabilidad por la recepción/no recepción o el 
                procesamiento/no procesamiento de cualquier información que el usuario haya transmitido desde y a unconviteporabejorral.org a través de la presente página web o a través de una dirección electrónica.</p>
                
                <h2>3. Propiedad intelectual</h2>
                <p>El contenido de esta página web y los datos de unconviteporabejorral.org están distribuidos bajo la 
                <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">Licencia Creative Commons Atribución-NoComercial-CompartirIgual 4.0 Internacional</a>
                 y el código fuente bajo la <a href="https://github.com/aleducode/help-abejorral/blob/master/LICENSE"> licencia MIT.</a></p>
                </div>

        </div>
    </div>
</div>        
{% endblock content %}

abjhelp/templates/thank_donor.html
{% extends 'base.html' %}

{% load static %}
{% block content %}

<div class="page-content">
    <div class="container-fluid">
        <div class="col-xl-4 offset-lg-4 mt-0 pt-0">
            <div class="card mt-0 pt-0">
                <div class="card-body mt-0 pt-0">
                    <h3 class="mt-0 pt-0 text-center">Listo</h3>
                    <div class="text-center">
                            <i class="bx bx-happy-beaming text-primary display-4"></i>
                        <div class="col-xs-4">
                            <div class="card bg-soft-primary">
                                <div class="row text-center">
                                    <div class="col-12">
                                        <div class="text-primary p-3 ">
                                            <h5 class="text-primary">¡Gracias por unirte!</h5>
                                            <p>Para nosotros es muy improtante tu ayuda. Muy pronto nos contactaremos contigo.</p>
                                        </div>
                                    </div>   
                                    <img src="{% static 'backoffice/assets/images/profile-img.png' %}" class="img-fluid" alt="Responsive image"
                                    class="img-fluid">  
                                </div>
                            </div>
                            <a href="{% url 'users:index' %}" class="btn btn-success btn-lg enabled" role="button"
                                aria-enabled="true">Regresar al inicio</a>
                        </div>
                        <div class="col-5 align-self-end">
                            <img src="assets/images/profile-img.png" alt="" class="img-fluid">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock content %}

abjhelp/templates/thanks.html
{% extends 'base.html' %}

{% load static %}
{% block content %}

<div class="page-content">
    <div class="container-fluid">
        <div class="col-xl-4 offset-lg-4 mt-0 pt-0">
            <div class="card mt-0 pt-0">
                <div class="card-body mt-0 pt-0">
                    <h3 class="mt-0 pt-0 text-center">Listo</h3>
                    <div class="text-center">
                        <div>
                            <i class="bx bx-happy-beaming text-primary display-4"></i>
                        </div>
                        <div class="col-xs-4 mt-0 pt-0 pb-0 mb-0">
                            <div class="card bg-soft-primary">

                                <div class="row text-center">
                                    <div class="col-12">
                                        <div class="text-primary p-3 ">
                                            <h5 class="text-primary">Solicitud recibida</h5>
                                            <p>La compartiremos con nuestros colaboradores y ellos te contactarán.</p>
                                            <a href="{% url 'users:index' %}">Regresar al inicio</a>
                                        </div>
                                    </div>   
                                    <img src="{% static 'backoffice/assets/images/profile-img.png' %}" class="img-fluid" alt="Responsive image"
                                    class="img-fluid">  
                                </div>
                            </div>
                            <a href="{% url 'users:index' %}" class="btn btn-success btn-lg enabled" role="button"
                                aria-enabled="true">Regresar al inicio</a>
                        </div>
                        <div class="col-5 align-self-end">
                            <img src="assets/images/profile-img.png" alt="" class="img-fluid">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock content %}